### ISSUE TITLE
No known class method for selector 'responseWithJSONObject:statusCode:headers:'

### ISSUE THREAD

**Issue by srosmd** [AliSoftware/OHHTTPStubs#121] opened 2015-09-23 17:17 UTC
Hey there,

Did a `pod install` of OHHTTPStubs this morning and got this error. Has this method been intentionally removed from `OHHTTPStubsResponse`? I checked my header file and noticed the method and its implementation were gone. 

If this was removed intentionally, what was the reasoning behind it? It's awfully convenient. :)

**Comment by AliSoftware** [comment] 2015-09-23 17:35
That's strange because I indeed separated that method in a dedicated subspec now, but that subspec should be included by default unless specified otherwise.

Can I see your `Podfile` and `Podfile.lock` files?

**Comment by srosmd** [comment] 2015-09-23 19:16
My `Podfile`:

	source 'https://github.com/CocoaPods/Specs.git'
	use_frameworks!

	pod 'AFNetworking', '~> 2.3'

	target 'MyAPI_Tests', :exclusive => true do
	  pod "MyAPI", :path => "../"
	  pod 'OHHTTPStubs' #, '~> 4.2.0' #I added this to fix the missing method
	  pod 'OCMock'
	  pod 'Expecta'
	end

 My 'Podfile.lock`:

PODS:
    - AFNetworking (2.6.0):
      - AFNetworking/NSURLConnection (= 2.6.0)
      - AFNetworking/NSURLSession (= 2.6.0)
      - AFNetworking/Reachability (= 2.6.0)
      - AFNetworking/Security (= 2.6.0)
      - AFNetworking/Serialization (= 2.6.0)
      - AFNetworking/UIKit (= 2.6.0)
    - AFNetworking/NSURLConnection (2.6.0):
      - AFNetworking/Reachability
      - AFNetworking/Security
      - AFNetworking/Serialization
    - AFNetworking/NSURLSession (2.6.0):
      - AFNetworking/Reachability
      - AFNetworking/Security
      - AFNetworking/Serialization
    - AFNetworking/Reachability (2.6.0)
    - AFNetworking/Security (2.6.0)
    - AFNetworking/Serialization (2.6.0)
    - AFNetworking/UIKit (2.6.0):
      - AFNetworking/NSURLConnection
      - AFNetworking/NSURLSession
    - Expecta (1.0.3)
    - OCMock (3.1.5)
    - OHHTTPStubs (4.3.0):
      - OHHTTPStubs/Default (= 4.3.0)
    - OHHTTPStubs/Core (4.3.0)
    - OHHTTPStubs/Default (4.3.0):
      - OHHTTPStubs/Core
      - OHHTTPStubs/JSON
      - OHHTTPStubs/NSURLSession
      - OHHTTPStubs/OHPathHelpers
    - OHHTTPStubs/JSON (4.3.0):
      - OHHTTPStubs/Core
    - OHHTTPStubs/NSURLSession (4.3.0):
      - OHHTTPStubs/Core
    - OHHTTPStubs/OHPathHelpers (4.3.0)
    - SIODeviceAPI (0.2.0-RC1):
      - AFNetworking (~> 2.3)

  DEPENDENCIES:
    - AFNetworking (~> 2.3)
    - Expecta
    - OCMock
    - OHHTTPStubs
    - SIODeviceAPI (from `../`)

  EXTERNAL SOURCES:
    SIODeviceAPI:
      :path: "../"

  SPEC CHECKSUMS:
    AFNetworking: 79f7eb1a0fcfa7beb409332b2ca49afe9ce53b05
    Expecta: 9d1bff6c8b0eeee73a166a2ee898892478927a15
    OCMock: 4c2925291f80407c3738dd1db14d21d0cc278864
    OHHTTPStubs: ea33adf65900e6bc8c31b80eb7d527e8874a559b
    SIODeviceAPI: d2f2d89d6be2295bc830a5eb155acf810a270f29

  COCOAPODS: 0.38.2

**Comment by AliSoftware** [comment] 2015-09-23 19:22
So I don't get it
1) your Podfile clearly shows that the `OHHTTPStubs/JSON` subspec has been retrieved by your `pod install` and is present, so you shouldn't have any problem
2) You added a comment in your Podfile saying you resolved the issue? So is it solved now or not? I'm a bit confused.

**Comment by srosmd** [comment] 2015-09-23 23:07
Hey Ali, 

Sorry if I was unclear. I worked around this issue by rolling back the version of OHHTTPStubs I was using to 4.2.1. However, when I've used 4.3.0, I get this error.

**Comment by AliSoftware** [comment] 2015-09-24 08:08
Ok, so as I was saying, if you don't specify the version you can see in your `Podfile.lock` that CocoaPods uses the `Default` subspec which in turn brings `OHHTTPStubs/Core`, `OHHTTPStubs/JSON`, `OHHTTPStubs/NSURLSession` and `OHHTTPStubs/OHPathHelper`.
So your project correctly has the subspec and the code that include the JSON additions, the code for JSON is there as expected.

So if you still have the « No known class method for selector 'responseWithJSONObject:statusCode:headers:' » error, maybe you forgot to add `#import <OHHTTPStubs/OHHTTPStubsResponse+JSON.h>` in your source file?
Agreed you should only need `#import <OHHTTPStubs/OHHTTPStubs.h>` (which is supposed to be the umbrella header and thus include that `OHHTTPStubsResponse+JSON.h` itself, but maybe the umbrella header stuff has been messed up by my recent split?)

Could you try adding `#import <OHHTTPStubs/OHHTTPStubsResponse+JSON.h>` to the source file where you want to call `responseWithJSONObject:statusCode:headers:` and see if it solves your error? If you had the error when `#import <OHHTTPStubs/OHHTTPStubs.h` but the error disappears when you `#import <OHHTTPStubs/OHHTTPStubsResponse+JSON.h`, it would probably mean that the cause of the issue would be a broken umbrella header (and you would have a workaround in the meantime).

**Comment by srosmd** [comment] 2015-09-24 16:11
Hey Ali, I'm happy to say your work around solved the issue. :) Thanks for your help. Seems like it might be a broken umbrella header then?

**Comment by AliSoftware** [comment] 2015-09-25 16:24
Yup, broken umbrella is probably the cause indeed. Will have to check it out sometime (but a little bit overwhelmed atm). Will keep this issue open to keep in mind that I have to investigate it.

**Comment by AliSoftware** [comment] 2015-10-01 18:21
I'm closing this as I opened a dedicated issue #127 to fix the umbrella header

**Closed by AliSoftware** 2015-10-01 18:21 UTC

**Comment by AliSoftware** [comment] 2015-10-24 12:11
Version `4.4.0` is out, fixing the umbrella header problem :wink:
