### ISSUE TITLE
HTTPBody nil workaround for Alamofire

### ISSUE THREAD

**Issue by JeanAzzopardi** [AliSoftware/OHHTTPStubs#143] opened 2015-12-09 15:59 UTC
Hi,
First off, thanks for the library - am having great fun using it.

I've run into issue - #52: (Body of request never makes it to stubRequestPassingTest), and there is a [workaround listed for AFNetworking](https://github.com/AliSoftware/OHHTTPStubs/wiki/Testing-for-the-request-body-in-your-stubs). 

What is the cleanest way to do the same thing with Alamofire?

**Comment by AliSoftware** [comment] 2015-12-09 19:57
Haven't tried achieving that with Alamofire, but it's definitely possible.

I just read the docs of Alamofire, and it seems that you can:

* Either implement your own `Alamofire.Manager` and override the `request` method and alike to make the same stuff as described in my wiki for AFN (store the body using `NSURLProtocol.setProperty(_, forKey:,inRequest:)`
* Or make an `extension Alamofire.Request` to add a method e.g. `storeBody()` which does that call, and use `Alamofire.request(…).storeBody().reponse { … }` everywhere in your app instead of `Alamofire.request(…).response { … }` (not as cool but should work and is opt-in at least)
* Use a `ParameterEncoding.Custom` parameter encoding in your requests, which will call the `ParameterEncoding.URL.encode()` method to build the request, then call the `NSURLProtocol` to store the body
* Swizzle `NSURLRequest.setBody()` in ObjC to call the original implementation then call `NSURLProtocol.setProperty(…)`
* Spam Apple with another dupe of the radar so they finally fix it :wink:

**Closed** 2016-01-31 20:22 UTC
