### ISSUE TITLE
SWIFT_VERSION not set correctly for Cocoapods

### ISSUE THREAD

**Issue by esetnik** [AliSoftware/OHHTTPStubs#231] opened 2016-12-13 20:32 UTC
Using Xcode 8.2 when building my targets I get the following issue on OHTTPStubs:

“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.

**Comment by AliSoftware** [comment] 2016-12-13 20:39
That's an issue on CocoaPods, not on OHHTTPStubs.

Basically, what CocoaPods does when you run `pod install` is that it uses the value of `SWIFT_VERSION` you have set on your own app project and set the same `SWIFT_VERSION` value for the Pods.xcodeproj targets.
So be sure to have set the right `SWIFT_VERSION` on your host project before running `pod install` (that's true for any Swift pod, not just `OHHTTPStubs`)

If the problem persists and you still have at least one target in the Pods.xcodeproj that doesn't have its `SWIFT_VERSION` build setting set, hence generating that Xcode prompt you're talking about:

* Ensure that you use the latest CocoaPods version
* Try to comment the line of the pod in your `Podfile`, run `pod install` (so it uninstalls the pod from your project), uncomment the pod line in your `Podfile` and run `pod install` again. This will force CocoaPods to regenerate the target for this pod in its `Pods.xcodeproj`. That's because if the SWIFT_VERSION wasn't set at the time of the first `pod install` or have changed since then, sometimes CocoaPods doesn't realize that the Pod target should change and leaves the pod target untouched.

If you still have an issue after all that, please file a bug on the CocoaPods repository, as it's an issue more related to CocoaPods not properly configuring the Pods project rather than specific to `OHHTTPStubs` itself.

**Comment by AliSoftware** [comment] 2016-12-15 20:31
It's aThis is confirmed with a lot of feedback from Twitter, Slack and the Dev forums, it's actually a regression also coming from Xcode 8.2, because Xcode 8.2 set back the `SWIFT_VERSION` to `3.0` but the "Use Legacy Swift Version" corresponding human readable settings in the Xcode GUI shows `No` for both values.

Th solution is to force-change the "Use Legacy Swift Version" for example by changing it to YES then back to NO again, to force Xcode to re-set it.

See also:

* https://twitter.com/arekholko/status/809120209491623936
* Confirmed [here by an Apple engineer working on Xcode](https://twitter.com/rballard/status/809452023007457280)

Closing this bug, as it has nothing to do with `OHHTTPStubs`.

**Comment by ikesyo** [comment] 2016-12-15 22:52
I'm sorry, mistook :bow:

**Closed by ikesyo** 2016-12-15 22:52 UTC
Labels: Invalid / Not a Bug

**Comment by esetnik** [comment] 2016-12-19 21:10
Hi @AliSoftware thanks for the feedback. I noticed the same thing but forgot to follow up here. I think it can also help to have the `.swift-version` file which might prevent this situation if Apple decides to cause this problem again.

See:
https://github.com/Alamofire/Alamofire/blob/master/.swift-version

**Comment by AliSoftware** [comment] 2016-12-19 22:00
Might be a good idea, but not sure that `.swift-version` would change anything. This file is used by CocoaPods to know which Swift version to _lint_ & _push_ your pod against, but doesn't affect the pod installation process.

See [our Blog Post here](http://blog.cocoapods.org/CocoaPods-1.1.0/#xcode-8-and-ios-10):

> In CocoaPods 1.1.0, setting the version of Swift when linting and pushing your pod is supported in following ways:
> […]
> * It uses the setting from your .swift-version file if present (inspired by swiftenv).

`pod install` always use the same `SWIFT_VERSION` that is set on your application target when installing and generating the Pods target, and doesn't use `.swift-version`; `.swift-version` is only used during `pod lib lint` / `pod spec lint` and `pod trunk push` / `pod repo push`
